apiVersion: v1
kind: Secret
metadata:
  name: bookshelf-secret
type: Opaque
stringData:
  DB_USER: "adminuser"
  DB_PASSWORD: "ChangeMeStrongPassword123!"
  JWT_SECRET: "your_super_secret_jwt_token_key"
