aws_region          = "us-east-1"
environment         = "prod"
vpc_cidr            = "10.0.0.0/16"
public_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs= ["10.0.10.0/24", "10.0.20.0/24"]
availability_zones  = ["us-east-1a", "us-east-1b"]
cluster_name        = "bookshelf-eks-cluster"
node_instance_type  = "c7i-flex.large"
desired_capacity    = 2
min_capacity        = 1
max_capacity        = 4
db_name             = "bookshelf_db"
db_username         = "admin"
db_password         = "Damodar123"
